config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get '/signup', to: 'employees#new'
  post '/signup', to: 'employees#create'

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	
  delete '/logout', to: 'sessions#logout', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :employees, only: [:new, :create, :show, :update, :edit] do
    resources :locations, only: [:new, :index]
  end

  resources :locations, except: [:index] do
    resources :measurements
  end

  get '/auth/:provider/callback', to: 'sessions#google'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :locations
    has_many :measurements
    has_many :measured_locations, through: :measurements, source: :location
    
    has_secure_password

    validates :username, presence: true, uniqueness: true

    validates :email, presence: true, uniqueness: true

    validates :contact_number, phone: { possible: true, allow_blank: true}, uniqueness: false
    before_save :format_phone

    def format_phone
        self.contact_number = Phonelib.parse(contact_number).national
    end
    
    scope :employee_most_locations, -> {joins(:locations).group:employee_id).order('count(locations.id) desc').limit(1)} 
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :employee
    has_many :measurements
    has_many :employees, through: :measurements

    validates :street_address, presence: true, uniqueness: true 
    validates :city, presence: true
    validates :state, presence: true
    validates :zip_code, presence: true

    scope :alpha, -> {order('street_address')}
end

app/models/measurement.rb
class Measurement < ApplicationRecord
    belongs_to :employee
    belongs_to :location
    
    validates :location, presence: true
    validates :length, presence: true
    validates :width, presence: true
    validates :date, presence: true

    scope :latest_date, -> {order(date: :desc)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private
    
    def current_user
        @current_user ||= Employee.find_by_id(session[:employee_id]) if session[:employee_id]
    end

    def logged_in?
        !!session[:employee_id]
    end

    def require_logged_in
        redirect_to '/login' if !logged_in?
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    def new
        @employee = Employee.new
    end

    def create 
       @employee = Employee.new(employee_params)
       if @employee.save
        session[:employee_id] = @employee.id
        redirect_to @employee
       else
        render :new
       end
    end


    def show
            require_logged_in
            find_employee
        if !@employee
            session.clear
            flash[:errors] = "That Employee Does Not Exist"
        end        
    end

    def edit
        find_employee
    end

    def update
        find_employee
       if @employee.update(employee_params)
         redirect_to employee_path(@employee)
       else
         render :edit
       end
     end


    private

    def employee_params
        params.require(:employee).permit(:username, :email, :contact_number, :password, :password_confirmation)
    end

    def find_employee
        @employee = Employee.find_by_id(params[:id])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :require_logged_in
    before_action :find_location, only: [:edit, :update, :show, :destroy]
    before_action :redirect_if_not_auth, only: [:edit, :update, :destroy]

    def new
        if employee_check
            @location = @employee.locations.build
        else
            @location = Location.new
        end
    end

    def index
      if params[:employee_id] && @employee = Employee.find_by_id(params[:employee_id])
        @locations = @employee.locations.alpha
      else
        session.clear
        flash[:errors] = "No Employee Found"
        redirect_to '/signup'
      end
    end

    def create 
        @location = current_user.locations.build(location_params)
        if @location.save
            redirect_to employee_locations_path(current_user)
        else
            render :new
        end
    end 



    def edit
    end

    def update
       if @location.update(location_params)
         redirect_to employee_locations_path(@location.employee)
       else
         render :edit
       end
     end

     def show
        redirect_to employee_locations_path if !@location
      end

      def destroy
        @location.destroy
    
        redirect_to employee_path(current_user)
      end
 
     private
 
     def location_params
         params.require(:location).permit(:employee_id, :city, :state, :street_address, :zip_code)
     end

     def employee_check
        @employee = Employee.find_by_id(params[:employee_id])
     end

     def find_location
        @location = Location.find_by_id(params[:id])
     end

     def redirect_if_not_auth
        redirect_to employee_path(current_user) if !@location || @location.employee != current_user
     end

end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :require_logged_in
  before_action :set_measurement, only: [:edit, :update, :destroy]

  
  def index
    if set_location
      @measurements = @location.measurements.latest_date
    else
      flash[:errors] = "That Location Does Not Exist" if !params[:location_id]
      redirect_to employee_locations_path(current_user)
    end
  end

  def new
    if set_location
      @measurement = @location.measurements.build
    else
      flash[:errors] = "That Location Does Not Exist" if !params[:location_id]
      @measurement = Measurement.new
    end
  end

  def create
    @measurement = current_user.measurements.build(measurement_params)
    if @measurement.save
      redirect_to employee_locations_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @measurement.update(measurement_params)
      redirect_to employee_locations_path(current_user)
    else
      flash[:errors] = "Unable to Update. Please Try Agian."
      redirect_to edit_location_measurement_path(@measurement)
    end
  end

  def destroy
    @measurement.destroy

    redirect_to employee_locations_path(current_user)
  end

  private

  def measurement_params
    params.require(:measurement).permit(:location_id, :length, :width, :date)
  end

  def set_measurement
    @measurement = Measurement.find_by_id(params[:id])
    if !@measurement
      flash[:errors] = "Measurement was not found"
      redirect_to employee_path(current_user)
    end
  end

  def set_location
    params[:location_id] && @location = Location.find_by_id(params[:location_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def create 
        employee = Employee.find_by_username(params[:username])
        if employee && employee.authenticate(params[:password])
            session[:employee_id] = employee.id
            redirect_to employee_path(employee)
        else
            flash[:errors] = "Invalid Login. Please Try Again."
            redirect_to '/login'
        end
    end

    def logout
        session.clear
        redirect_to new_employee_path
    end

    def google
        employee = Employee.find_or_create_by(uid: request.env['omniauth.auth'][:uid], provider: request.env['omniauth.auth'][:provider]) do |emp|
            emp.username = request.env['omniauth.auth'][:info][:name]
            emp.email = request.env['omniauth.auth'][:info][:email]
            emp.password = SecureRandom.hex(15)
        end
        if employee.valid?
            session[:employee_id] = employee.id
            redirect_to employee_path(employee.id)
        else
            redirect_to login_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper

    def employees_locations
        if @employee
            "#{@employee.username}'s Locations"
        else
            'Please Sign In or Sign Up'
        end
    end


end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/employees/_employees.html.erb
<%= form_for @employee do |f| %>
    <div>
    <%= render partial: "layouts/errors", locals: {record: @employee} %>
    <%= f.label :username%>
    <%= f.text_field :username %></br></br>
    <%= f.label :email%>
    <%= f.email_field :email %></br></br>
    <%= f.label :contact_number, 'Contact Number' %>
    <%= f.phone_field :contact_number %></br>
    * Include Area Code. Ex: 1112223333 or 111-222-3333
    </br></br>
    <%= f.label :password %>
    <%= f.password_field :password %></br></br>
    <%= f.label :password_confirmation%>
    <%= f.password_field :password_confirmation %></br></br>
    <%= f.submit "Submit"  %>
    </div>
<% end %>

app/views/employees/edit.html.erb
<h1> Update Contact Information </h1>

<%= render partial: "employees", locals: {employee_new: @employee} %>

app/views/employees/new.html.erb
<h1> Welcome! </h1>
<h2> Complete the Form Below to Create a Profile.</h2>

<%= render partial: "employees", locals: {employee_new: @employee} %>

</br> Or 
<h5><%= link_to 'Login with Google', '/auth/google_oauth2' %></h5>

app/views/employees/show.html.erb
<h1> <%= @employee.username %>'s Profile </h1>
<p> Email: <%= @employee.email %> </p>
<p> Contact Number: <%= @employee.contact_number %> </p>
<p><%= link_to 'Employee Measured Locations', employee_locations_path(@employee) %></p> 
<p><%= link_to 'Update Contact Information', edit_employee_path(@employee) %></p> </br>

app/views/layouts/_errors.html.erb
<% if record.errors.any? %>
    <ul class="errors">
    <% record.errors.each do |error| %>
        <li><%= error.full_message %></li>
    <% end %>
    </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-danger">
    <%= msg %>
  </div>
<% end %>
        

app/views/layouts/_nav.html.erb
<nav>
<% if logged_in? %>
    <%= link_to "Logout", logout_path, method: 'delete' %> |||
    <%= link_to "Add A New Location", new_employee_location_path(current_user) %> |||
    <%= link_to "Employee Locations", employee_locations_path(current_user) %>  |||
    <%= link_to "Profile", employee_path(current_user) %></br></br>
<% else %>
    <%= link_to 'Login', login_path %> |||
    <%= link_to 'Create a New Profile', new_employee_path %></br></br>
<% end %>    
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>RockJobs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/stylesheets/application.css" />
  </head>

  <body style="background-color:#E9F0FF;">
  
    <%= render "layouts/nav" %>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/locations/_locations.html.erb
<%= form_for @location do |f| %>
    <%= render partial: "layouts/errors", locals: {record: @location} %>
    <%= f.label :street_address %>
    <%= f.text_field :street_address %></br></br>
    <%= f.label :city%>
    <%= f.text_field :city %></br></br>
    <%= f.label :state %>
    <%= f.text_field :state %>  </br></br>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %></br></br>
    <%= f.submit "Submit"  %>
    <%= %>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit <%= @location.street_address %></h1>

<%= render partial: "locations", locals: {edit_location: @location} %>

app/views/locations/index.html.erb
<h1> <%= employees_locations %> </h1></br></br>


<% if @locations == [] %>
  <h5> This Employee Has No Measured Locations </h5>
    <%= link_to "Back to Profile Page", employee_path(current_user) %></br></br>
    <%= link_to "Add A New Location", new_employee_location_path(current_user) %>

  <% else %>
  <ul>
<% @locations.each do |loc|%>
  <li><%= loc.street_address %> - <%= link_to 'View', location_measurements_path(loc) %> - <%= link_to 'Edit', edit_location_path(loc.id) %> - <%= link_to "Delete", location_path(loc.id), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>
</ul>
<% end %>

app/views/locations/new.html.erb
<h1> New Location </h1>

<%= render partial: "locations", locals: {location_employee: @location} %>

app/views/locations/show.html.erb
<h1><%= @location.street_address %></h1>
<h2><%= @location.city %>, <%= @location.state %></h2>

<p><%= link_to 'Add A New Measurement', new_measurement_path(@location)%></p>

<% if !@location.measurements.empty? %>
  <p><%= link_to 'See All Measurements', location_measurements_path(@location)%></p>
  <h4>Most Recent Measurements:</h4>
  <% @location.measurements.order(date: :desc).limit(3).each do |loc|%>
    <li>
      <strong><%= loc.employee.username%> - <%= loc.date %> - <%= link_to 'View', location_measurements_path(@location)%> </strong> 
    </li>
  <% end %>
  
<% end %>

app/views/measurements/_measurements.html.erb
  <%= form_for([@measurement.location, @measurement]) do |f|%>
  <%= render partial: "layouts/errors", locals: {record: @measurement} %> 
  <%= f.label :location %>
  <%= f.text_field :location, value: @measurement.location.street_address %></br></br>
  <%= f.label :length %>
  <%= f.number_field :length %></br></br>
  <%= f.label :width %>
  <%= f.number_field :width %></br></br>
  <%= f.label :date %>
  <%= f.date_field :date %></br></br>
  <%= f.hidden_field :location_id %>
  <%= f.submit %>
<% end %>

app/views/measurements/edit.html.erb
<h1> Edit Measurement </h1>

<%= render partial: "measurements", locals: {edit_measurement: @measurement} %>

app/views/measurements/index.html.erb
<% if @location %>
    <h1> <%= @location.street_address %> </h1>
<% else %>
    <h1> Please Sign In or Sign Up </h1>
<% end %>

<% if @measurements == [] %></br></br>
  <h5> This Location Has No Measurements </h5>
  <% else %>
<ul>
<% @measurements.each do |m|%>
  <li><%= m.employee.username %> - <%= m.length %>" x <%= m.width %>" - <%= link_to 'Edit', edit_location_measurement_path(@location, m.id)%> - <%= link_to "Delete", location_measurement_path(@location, m.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </br>Measured On: <%= m.date %> </br></br>
<% end %>
</ul>
<% end %>

<p><%= link_to 'Add A New Measurement', new_location_measurement_path(@location)%></p>

app/views/measurements/new.html.erb
<h1>New measurement for <%= @measurement.location.street_address %></h1>

<%= render partial: "measurements", locals: {edit_measurement: @measurement} %>